import test from 'node:test';
import assert from 'node:assert/strict';
import {newState,beginSession,drawCard,cardPool,recordResult,advanceTurn,addToBoard,moveBoardCard,normalizeState,loadState,saveState} from '../src/engine.js';
import {CARDS,PACKS} from '../src/data.js';
const session=()=>beginSession(newState(),['Ada','Bo','Cleo'],3);
test('invalid player setup is rejected and names are unique',()=>{assert.throws(()=>beginSession(newState(),['One']));assert.throws(()=>beginSession(newState(),['One','one']));assert.equal(beginSession(newState(),[' Ada ','Bo','Ada']).players.length,2);});
test('every pack and level has playable cards',()=>{for(const pack of PACKS)for(let level=1;level<=5;level++){const s={...session(),pack:pack.id,level};assert.ok(cardPool(s).length>=4);assert.ok(cardPool(s).every(c=>c.level<=level&&c.pack===pack.id));}});
test('smart random exhausts eligible pool before repeating',()=>{const s=session(),length=cardPool(s).length;const ids=Array.from({length},()=>drawCard(s,null,()=>0).id);assert.equal(new Set(ids).size,length);assert.ok(drawCard(s,null,()=>0));});
test('rounds advance after all players and finish at the configured limit',()=>{const s=session();for(let i=0;i<8;i++){advanceTurn(s);assert.equal(s.finished,false);}advanceTurn(s);assert.equal(s.finished,true);assert.equal(s.round,3);assert.equal(s.turn,9);});
test('result history and board snapshots are independent and deduplicated',()=>{const s=session(),card=drawCard(s);recordResult(s,card,'dice');assert.equal(addToBoard(s),true);assert.equal(addToBoard(s),false);s.result.card.title='Changed';assert.notEqual(s.board[0].card.title,'Changed');advanceTurn(s);assert.equal(s.result,null);assert.equal(s.board.length,1);assert.equal(s.history.length,1);});
test('board reorder is bounded and preserves all cards',()=>{const s=session();for(let i=0;i<3;i++){recordResult(s,drawCard(s),'cards');addToBoard(s);}const id=s.board[0].id;moveBoardCard(s,id,-1);assert.equal(s.board[0].id,id);moveBoardCard(s,id,1);assert.equal(s.board[1].id,id);assert.equal(new Set(s.board.map(c=>c.id)).size,3);});
test('category and intensity constraints apply to own cards',()=>{const s=session();s.category='wildcard';s.level=1;assert.equal(drawCard(s),null);s.customCards=[{id:'custom-test',pack:'all',category:'wildcard',level:1,title:'Own card',text:'Hello',seconds:10}];assert.equal(drawCard(s).id,'custom-test');});
test('new sessions retain custom cards and settings but clear past play',()=>{const s=session();s.settings.sound=true;s.customCards.push({...CARDS[0],id:'custom-test'});recordResult(s,drawCard(s),'slots');addToBoard(s);const fresh=beginSession(s,['Ada','Bo']);assert.equal(fresh.history.length,0);assert.equal(fresh.board.length,0);assert.equal(fresh.customCards.length,1);assert.equal(fresh.settings.sound,true);});
test('storage roundtrip and corrupt storage recovery',()=>{let value;const storage={getItem:()=>value,setItem:(_,v)=>value=v};const s=session();recordResult(s,drawCard(s),'slots');addToBoard(s);assert.equal(saveState(storage,s),true);const restored=loadState(storage);assert.equal(restored.players[0].name,'Ada');assert.equal(restored.board.length,1);value='{';assert.equal(loadState(storage).started,false);assert.equal(saveState({setItem:()=>{throw Error();}},s),false);});
test('invalid imported settings and HTML-bearing ids are rejected',()=>{const s=session();s.engine='broken';s.active=900;s.settings.theme='broken';s.customCards=[{...CARDS[0],id:'" onclick="alert(1)'}];const clean=normalizeState(s);assert.equal(clean.engine,'slots');assert.equal(clean.active,2);assert.equal(clean.settings.theme,'neon');assert.equal(clean.customCards.length,0);assert.equal(normalizeState(null).started,false);});
test('import rejects malformed engine transitions and timer payloads',()=>{const s=session();s.customCards=[{...CARDS[0],nextEngine:'unknown'},{...CARDS[1],seconds:-100}];assert.equal(normalizeState(s).customCards.length,0);});

