import { ENGINES, CATEGORIES, PACKS, CARDS, LEVELS, IDEAS } from './data.js';
import { loadState, saveState, normalizeState, beginSession, drawCard, recordResult, advanceTurn, addToBoard, moveBoardCard, cardPool, randomInt, uid } from './engine.js';
const app=document.querySelector('#app');
let storage; try { storage=window.localStorage; } catch { storage={getItem:()=>null,setItem:()=>{throw new Error('Storage unavailable');}}; }
let state=loadState(storage);
let page='play', busy=false, collapsed=false, drawer=false, modal='', modalData=null, timerId=null, timerRemaining=0, timerRunning=false, finaleIndex=0, toastId;
let diceValues=[3,5], slotValues=['bolt','star','gift'], wheelAngle=0, selectedBox=-1, editId=null;
const paths={
 home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',play:'m9 5 11 7-11 7Z',pause:'M8 5v14M16 5v14',bolt:'m13 2-9 12h7l-1 8 10-12h-7Z',
 dice:'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2ZM8 8h.01M16 8h.01M12 12h.01M8 16h.01M16 16h.01',
 slots:'M3 5h16v15H3ZM8 5v15M14 5v15M21 6v8h-2M5 11l1 1-1 2M10 11l1 1-1 2M16 11l1 1-1 2',
 wheel:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20ZM12 2v7M12 15v7M2 12h7M15 12h7M5 5l5 5M14 14l5 5M5 19l5-5M14 10l5-5M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z',
 cards:'M7 3h13v17H7ZM4 5l-2 14 3 1M11 8l5 3-5 3Z',gift:'M3 8h18v4H3ZM5 12v9h14v-9M12 8v13M12 8C3 8 5 0 9 3l3 5Zm0 0c9 0 7-8 3-5l-3 5Z',shuffle:'M3 6h3c5 0 7 12 12 12h3M18 15l3 3-3 3M3 18h3c2 0 4-3 5-5M14 8c1-1 2-2 4-2h3M18 3l3 3-3 3',
 users:'M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM2 21v-3a6 6 0 0 1 12 0v3M16 4a4 4 0 0 1 0 8M17 15a5 5 0 0 1 5 5v1',star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z',flame:'M12 2c1 6-5 6-5 12a5 5 0 0 0 10 0c0-2-1-4-2-5 0 3-2 3-2 3s2-5-1-10Z',heart:'M20 4a5 5 0 0 0-8 2 5 5 0 0 0-8-2c-5 5 8 16 8 16S25 9 20 4Z',sparkles:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5ZM20 2v4M18 4h4',
 chat:'M21 11a9 9 0 0 1-9 9H4l-2 2V11a9 9 0 0 1 19 0ZM7 10h10M7 14h6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM9 2h6l1 3 3 1 3 3v6l-3 1-1 3-3 3H9l-1-3-3-1-3-3V9l3-1 1-3Z',palette:'M12 3a9 9 0 1 0 0 18h1a2 2 0 0 0 1-4c-1-2 1-3 3-3h2c4 0 2-11-7-11ZM7 9h.01M11 6h.01M16 8h.01M6 14h.01',studio:'m14 4 6 6M3 21l2-6L17 3a2 2 0 0 1 4 4L9 19ZM3 21l6-2',
 chevron:'m9 5 7 7-7 7',down:'m5 9 7 7 7-7',close:'m6 6 12 12M6 18 18 6',plus:'M12 4v16M4 12h16',check:'m4 12 5 5L20 6',volume:'M11 4 6 8H2v8h4l5 4ZM15 8a6 6 0 0 1 0 8M18 4a11 11 0 0 1 0 16',mute:'M11 4 6 8H2v8h4l5 4ZM16 9l6 6M16 15l6-6',arrow:'M4 12h16m-6-6 6 6-6 6',back:'M20 12H4m6-6-6 6 6 6',clock:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20ZM12 6v6l4 2',flag:'M4 22V3c7-5 9 5 16 0v11c-7 5-9-5-16 0',trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7',download:'M12 3v12m-5-5 5 5 5-5M3 16v5h18v-5',upload:'M12 16V4m-5 5 5-5 5 5M3 16v5h18v-5',crown:'m2 6 5 5 5-8 5 8 5-5-3 13H5ZM5 22h14',shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6Z',menu:'M4 6h16M4 12h16M4 18h16',trophy:'M7 3h10v8a5 5 0 0 1-10 0ZM7 5H3v4a4 4 0 0 0 4 4M17 5h4v4a4 4 0 0 1-4 4M12 16v5M7 21h10',book:'M12 5C8 2 4 2 2 3v16c4-1 7 0 10 2 3-2 6-3 10-2V3c-2-1-6-1-10 2ZM12 5v16',history:'M3 11a9 9 0 1 1 2 7M3 4v7h7M12 7v5l4 2'
};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.sparkles}"/>${name==='dice'?'<circle cx="8" cy="8" r="1" fill="currentColor"/><circle cx="16" cy="16" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/>':''}</svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const engine=()=>ENGINES.find(e=>e.id===state.engine),pack=()=>PACKS.find(p=>p.id===state.pack),current=()=>state.players[state.active],category=id=>CATEGORIES.find(c=>c.id===id)||CATEGORIES[0];
const btn=(action,text,ico,cls='button',attrs='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${ico?icon(ico):''}${text}</button>`;
const option=(value,label,selected)=>`<option value="${esc(value)}" ${selected===value?'selected':''}>${esc(label)}</option>`;
function persist(){if(!saveState(storage,state))toast('Din browser kunne ikke gemme. Eksportér aftenen i Indstillinger.');}
function toast(message){clearTimeout(toastId);const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');toastId=setTimeout(()=>el.classList.remove('show'),3300);}
function tone(freq=660){if(!state.settings.sound)return;try{const ctx=new(window.AudioContext||window.webkitAudioContext)();const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.connect(gain);gain.connect(ctx.destination);oscillator.frequency.value=freq;gain.gain.setValueAtTime(.045,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18);oscillator.start();oscillator.stop(ctx.currentTime+.2);oscillator.onended=()=>ctx.close();}catch{}}
const delay=ms=>new Promise(resolve=>setTimeout(resolve,state.settings.motion?ms:40));
function stopTimer(){clearInterval(timerId);timerId=null;timerRunning=false;}
function render(){
 document.documentElement.dataset.theme=state.settings.autoTheme?pack().theme:state.settings.theme;
 document.documentElement.classList.toggle('reduce-motion',!state.settings.motion);
 app.innerHTML=`<div class="app-shell ${collapsed?'nav-collapsed':''}"><aside class="sidebar"><a class="brand" href="#play" aria-label="LEG & DRUK hjem"><span class="brand-symbol">&</span><span class="brand-name">LEG <b>&</b> DRUK<small>LET THE GOOD TIMES ROLL</small></span></a><span class="nav-label">DIT COMMAND CENTER</span><nav aria-label="Hovednavigation">${[['play','play','Spil nu'],['board','bolt','Action Board'],['engines','dice','Spilmotorer'],['packs','gift','Spilpakker']].map(([id,ico,label])=>navItem(id,ico,label)).join('')}<div class="nav-divider"></div>${[['ideas','sparkles','Idérum'],['studio','studio','Studio'],['design','palette','Design']].map(([id,ico,label])=>navItem(id,ico,label)).join('')}</nav><div class="sidebar-bottom"><div class="master-promo">${icon('crown')}<span>Du styrer aftenen<small>Dit bord. Dine regler.</small></span></div>${navItem('settings','settings','Indstillinger')}${btn('collapse',collapsed?'':'Fold menu sammen','menu','collapse-button',`aria-label="${collapsed?'Udvid':'Fold'} menu"`)}</div></aside>
 <div class="workspace"><header class="topbar"><div class="breadcrumb">Command Center ${icon('chevron')} <span>${({play:'Spil nu',board:'Action Board',engines:'Spilmotorer',packs:'Spilpakker',ideas:'Idérum',studio:'Studio',design:'Design',settings:'Indstillinger',finale:'Finale'})[page]}</span></div><div class="top-actions"><span class="session-status"><i class="status-dot ${state.started&&!state.paused&&!state.finished?'live':''}"></i>${state.finished?'Aften afsluttet':state.started?(state.paused?'På pause':'Aftenen er i gang'):'Klar til en god aften'}</span>${btn('sound','',state.settings.sound?'volume':'mute','icon-button',`aria-label="${state.settings.sound?'Slå lyd fra':'Slå lyd til'}" title="Lyd"`)}${btn('help','','book','icon-button','aria-label="Sådan spiller I" title="Sådan spiller I"')}<span class="mini-brand">&</span></div></header><main id="main" class="main ${page==='play'?'play-layout':''}">${pageContent()}</main><footer class="app-footer"><span>LEG & DRUK <span class="footer-dot">·</span> Skabt til gode aftener</span><span>${icon('shield')} Plads til alle. Altid okay at springe over.</span></footer></div>
 ${drawer?`<div class="drawer-backdrop" data-action="close-drawer"></div><section class="board-drawer" aria-label="Action Board"><div class="section-heading"><div><span class="eyebrow">AFTENENS SAMLING</span><h2>Action Board <span class="count">${state.board.length}</span></h2></div>${btn('close-drawer','','close','icon-button','aria-label="Luk Action Board"')}</div>${boardContent()}</section>`:''}</div>${modal?modalHTML():''}`;
 if(modal){const dialog=document.querySelector('dialog');dialog.showModal();requestAnimationFrame(()=>(dialog.querySelector('[autofocus]')||dialog.querySelector('input, button'))?.focus());}
 if(timerRemaining>0)updateTimer();
}
function navItem(id,ico,label){return `<button class="nav-item ${page===id?'active':''}" data-page="${id}" title="${label}" ${page===id?'aria-current="page"':''}>${icon(ico)}<span>${label}</span>${id==='board'&&state.board.length?`<b class="nav-count">${state.board.filter(c=>!c.done).length}</b>`:''}${id==='studio'?'<small>SKAB</small>':''}</button>`;}
function pageContent(){switch(page){case'play':return playPage();case'board':return pageHeader('AFTENENS SAMLING','Action Board','Gem udfordringer. Fordel dem. Afvikl dem, når det passer jer.',btn('finale','Start finalen','flag','button primary',state.board.some(c=>!c.done)?'':'disabled'))+boardContent();case'engines':return enginesPage();case'packs':return packsPage();case'ideas':return ideasPage();case'studio':return studioPage();case'design':return designPage();case'settings':return settingsPage();case'finale':return finalePage();default:return playPage();}}
function pageHeader(kicker,title,description,action=''){return `<div class="page-heading"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${description}</p></div>${action}</div>`;}
function playPage(){if(state.finished)return summaryPage();return `<section class="game-column"><div class="page-heading play-heading"><div><span class="eyebrow">GODE VENNER. UFORUDSIGELIGE AFTENER.</span><h1>Lad aftenen <em>spille.</em></h1></div>${btn('setup',state.started?'Nyt spil':'Tilføj spillere','plus','button secondary')}</div><div class="pack-strip"><div class="pack-mark">${icon(pack().icon)}</div><div><small>AKTIV SPILPAKKE</small><strong>${pack().name}</strong></div><span class="pack-type">${state.settings.alcohol?'18+ · Med drikkevalg':'Alkoholfri'}</span>${btn('packs','Skift pakke','chevron','text-button')}</div><section class="game-stage ${busy?'is-busy':''} ${state.result?'has-result':''}" aria-label="${engine().name}"><div class="stage-top"><span class="stage-tag">${icon(engine().icon)} ${engine().name}</span><span class="round-tag">RUNDE <b>${String(state.round).padStart(2,'0')}</b> <span>/ ${state.rounds}</span></span></div>${state.paused?`<div class="pause-state">${icon('pause')}<span class="eyebrow">TAG JER GOD TID</span><h2>Aftenen er på pause</h2><p>Vi holder pladsen til jer.</p>${btn('pause','Fortsæt spillet','play','button primary')}</div>`:state.result?resultContent():machineContent()}<div class="stage-footer"><span>${icon('shield')} ${state.settings.smart?'Smart Random er aktiv':'Tilfældig rækkefølge'}</span><span>${icon('users')} ${state.players.length||'2–16'} spillere</span></div></section><div class="engine-dock" role="group" aria-label="Vælg spilmotor">${ENGINES.map(e=>`<button data-engine="${e.id}" class="dock-item ${state.engine===e.id?'selected':''}" ${busy?'disabled':''} aria-pressed="${state.engine===e.id}">${icon(e.icon)}<span>${e.name}</span>${state.engine===e.id?'<i></i>':''}</button>`).join('')}</div><button class="board-bar" data-action="drawer"><span class="board-bar-icon">${icon('bolt')}</span><span><strong>Action Board</strong><small>Gem aftenens udfordringer til senere</small></span><span class="pill">${state.board.filter(c=>!c.done).length} kort</span>${icon('chevron')}</button></section><aside class="control-column">${controlPanel()}${recentPanel()}</aside>`;}
function machineContent(){return `<div class="machine-content"><span class="eyebrow machine-kicker">${busy?'SKÆBNEN ARBEJDER …':engine().label}</span><h2>${engine().name}<span class="heading-spark">✦</span></h2><p class="machine-description">${engine().note}</p><div class="mechanism ${state.engine}" id="mechanism">${mechanism()}</div><div class="chain-trail">${state.chain.length?state.chain.map(s=>`<span>${esc(s)}</span>`).join(icon('chevron')):'<span>ET SPIN KAN STARTE NOGET STORT</span>'}</div>${state.engine==='mystery'?`<p class="mystery-hint">${busy?'Låser hemmeligheden op …':'Tryk på en boks for at afsløre din udfordring'}</p>`:btn('play',busy?'SPÆNDINGEN STIGER …':state.started?engine().verb:'START AFTENEN','bolt','play-button',busy?'disabled':'')}<div class="stage-subactions">${btn('pause','Pause','pause','text-button',!state.started||busy?'disabled':'')}${btn('skip','Spring over','arrow','text-button',!state.started||busy?'disabled':'')}</div></div>`;}
function mechanism(){switch(state.engine){case'slots':return `<div class="slot-machine"><div class="slot-brand">LEG <b>&</b> DRUK <span>LUCKY SERIES / 01</span></div><div class="reels">${slotValues.map((s,i)=>`<div class="reel reel-${i} ${busy?'rolling':''}"><div class="reel-ghost">${icon(['heart','star','flame'][i])}</div><div class="reel-main">${icon(s)}</div><div class="reel-ghost">${icon(['gift','bolt','heart'][i])}</div></div>`).join('')}</div><div class="machine-trim"><i></i><span>GOOD TIMES • NO LIMITS</span><i></i></div><div class="slot-lever"><span></span></div></div>`;
case'dice':return `<div class="dice-pair ${busy?'rolling':''}">${diceValues.map(n=>`<div class="die" aria-label="${n}">${Array.from({length:9},(_,i)=>`<i class="pip ${({1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]})[n].includes(i)?'visible':''}"></i>`).join('')}</div>`).join('')}</div>`;
case'roulette':return `<div class="roulette-wrap"><div class="wheel-pointer"></div><div class="roulette-wheel" style="--wheel-angle:${wheelAngle}deg">${CATEGORIES.map((c,i)=>`<span class="wheel-label" style="--angle:${i*72+36}deg">${icon(c.icon)}</span>`).join('')}<div class="wheel-center">&</div></div></div>`;
case'cards':return `<div class="card-stack ${busy?'drawing':''}"><div></div><div></div><div><span>LEG & DRUK</span><b>&</b><small>LEAVE IT TO THE CARDS</small></div></div>`;
case'mystery':return `<div class="mystery-grid">${Array.from({length:12},(_,i)=>`<button data-box="${i}" class="mystery-box ${selectedBox===i?'chosen':''}" aria-label="Åbn mystery box ${i+1}" ${busy?'disabled':''}>${icon('gift')}<span>${String(i+1).padStart(2,'0')}</span></button>`).join('')}</div>`;
case'random':return `<div class="random-orbit ${busy?'spinning':''}">${ENGINES.slice(0,5).map((e,i)=>`<span style="--i:${i}">${icon(e.icon)}</span>`).join('')}<b>?</b></div>`;}}
function resultContent(){const r=state.result,c=category(r.card.category),saved=state.board.some(x=>x.sourceId===r.id);return `<div class="result-wrap"><span class="eyebrow result-label">${icon('check')} RESULTATET ER LANDET</span><article class="result-card" style="--card-color:${c.color}"><div class="result-category">${icon(c.icon)} ${c.name}<span>${'●'.repeat(r.card.level)}${'○'.repeat(5-r.card.level)}</span></div><span class="result-player">${esc(r.playerName)}, din tur</span><h2>${esc(r.card.title)}</h2><p>${esc(r.card.text)}</p>${state.settings.alcohol?'<small class="drink-note">Valgfrit: Skål med din yndlingsdrik, når I er færdige.</small>':''}${r.card.seconds?`<button class="timer-button" data-action="timer">${icon('clock')} <span id="timer-value">${timerRemaining||r.card.seconds}s</span> <span id="timer-label">${timerRunning?'Pause timer':'Start timer'}</span></button>`:''}</article><div class="result-actions">${btn(r.card.nextEngine&&state.chain.length<8?'continue-chain':'next',r.card.nextEngine&&state.chain.length<8?'Fortsæt med '+ENGINES.find(e=>e.id===r.card.nextEngine).name:'Næste spiller','arrow','button primary')}${btn('save',saved?'Gemt på board':'Gem på board',saved?'check':'plus','button secondary',saved?'disabled':'')}</div><div class="stage-subactions">${btn('pause','Pause','pause','text-button')}${btn('skip','Spring over','arrow','text-button')}</div></div>`;}
function controlPanel(){const p=current();return `<section class="control-panel"><div class="section-label">GAME CONTROL ${icon('settings')}</div><div class="active-player"><div class="avatar-ring"><span>${p?esc(p.name.slice(0,2).toUpperCase()):icon('users')}</span><i>${icon('bolt')}</i></div><span class="eyebrow">${state.started?'AKTIV SPILLER':'SAML DIT HOLD'}</span><h2>${p?esc(p.name):'Hvem er med?'}</h2><p>${state.started?'Din tur til at sætte gang i aftenen':'Tilføj vennerne, og sæt spillet i gang'}</p></div><div class="players-row">${state.players.slice(0,8).map((p,i)=>`<span class="small-avatar color-${i%4} ${i===state.active?'current':''}" title="${esc(p.name)}">${esc(p.name.slice(0,1))}</span>`).join('')}${btn('players','','plus','add-player','aria-label="Rediger spillere"')}</div><div class="control-divider"></div><div class="intensity-header"><label for="intensity">INTENSITET</label><strong>${LEVELS[state.level-1]}</strong></div><input id="intensity" type="range" min="1" max="5" value="${state.level}" aria-valuetext="${LEVELS[state.level-1]}" ${busy?'disabled':''}/><div class="range-labels"><span>Helt chill</span><span>All in ${icon('flame')}</span></div><div class="control-divider"></div><div class="control-info"><span>Spilmotor</span><strong>${icon(engine().icon)} ${engine().name}</strong></div><div class="control-info"><span>Næste spiller</span><strong>${state.players.length?esc(state.players[(state.active+1)%state.players.length].name):'–'}</strong></div><div class="control-info"><span>Spilletid</span><strong>${state.rounds} runder</strong></div>${btn('master','Game Master','crown','master-button',!state.started||busy?'disabled':'')}</section>`;}
function recentPanel(){return `<section class="recent-panel"><div class="section-label">SENESTE I AFTEN ${icon('history')}</div>${state.history.length?state.history.slice(0,3).map(h=>`<button class="recent-item" data-history="${esc(h.id)}"><span class="recent-icon" style="color:${category(h.card.category).color}">${icon(category(h.card.category).icon)}</span><span><strong>${esc(h.playerName)}</strong><small>${esc(h.card.title)}</small></span>${icon('chevron')}</button>`).join(''):`<div class="empty-history">${icon('sparkles')}<p>De gode historier<br>starter med første spil.</p></div>`}<div class="live-caption"><i></i> Aftenens øjeblikke, samlet ét sted</div></section>`;}
function boardContent(){if(!state.board.length)return `<div class="empty-state">${icon('bolt')}<h2>De bedste udfordringer fortjener en encore.</h2><p>Tryk “Gem på board”, når et resultat lander.<br>Her kan I fordele, flytte og gennemføre kortene.</p>${btn('go-play','Tilbage til spillet','play','button primary')}</div>`;return `<div class="board-toolbar"><span>${state.board.filter(c=>c.done).length} af ${state.board.length} gennemført</span><label>Vis <select id="board-filter"><option value="all">Alle kort</option><option value="pending">Ikke gennemført</option><option value="done">Gennemført</option></select></label></div><div class="board-grid">${state.board.map((item,i)=>`<article class="board-card ${item.done?'completed':''}" data-board-id="${item.id}" draggable="true"><div class="board-card-top"><span style="color:${category(item.card.category).color}">${icon(category(item.card.category).icon)} ${category(item.card.category).name}</span><small>#${String(i+1).padStart(2,'0')}</small></div><button class="board-open" data-open-card="${item.id}"><h3>${esc(item.card.title)}</h3><p>${esc(item.card.text)}</p></button><label class="board-assignee">${icon('users')}<select data-assign="${item.id}" aria-label="Spiller for ${esc(item.card.title)}">${state.players.map(p=>option(p.id,p.name,item.playerId)).join('')}</select></label><div class="board-card-actions">${btn('board-done',item.done?'Gennemført':'Markér færdig','check',`text-button ${item.done?'done':''}`,`data-id="${item.id}"`)}<span>${btn('move-up','','back','icon-button',`data-id="${item.id}" aria-label="Flyt kort tidligere" ${i===0?'disabled':''}`)}${btn('move-down','','arrow','icon-button',`data-id="${item.id}" aria-label="Flyt kort senere" ${i===state.board.length-1?'disabled':''}`)}${btn('remove-card','','trash','icon-button',`data-id="${item.id}" aria-label="Fjern kort"`)}</span></div></article>`).join('')}</div>`;}
function enginesPage(){return pageHeader('ÉN AFTEN. MANGE MULIGHEDER.','Vælg din spilmotor','Skift spillets form, og behold spillere, runde og Action Board.')+`<div class="selection-grid">${ENGINES.map(e=>`<button class="selection-card engine-card ${state.engine===e.id?'chosen':''}" data-engine="${e.id}"><div class="selection-icon">${icon(e.icon)}</div><span class="eyebrow">${e.id==='random'?'ALT KAN SKE':'GAME ENGINE'}</span><h2>${e.name}</h2><p>${e.note}</p><span class="selection-cta">${state.engine===e.id?'Aktiv spilmotor':'Vælg spilmotor'} ${icon('arrow')}</span></button>`).join('')}</div>`;}
function packsPage(){return pageHeader('FIND AFTENENS STEMNING','Spilpakker','Fire verdener. Samme bord. Vælg den, der passer til jer.')+`<div class="selection-grid packs-grid">${PACKS.map(p=>`<article class="selection-card pack-card ${p.color} ${state.pack===p.id?'chosen':''}"><div class="pack-card-art">${icon(p.icon)}<span>${p.id==='party'?'LET’S PLAY':p.id==='chaos'?'GO WILD':p.id==='duo'?'JUST US':'GOOD TIMES'}</span></div><div class="pack-card-body"><span class="eyebrow">${p.tag}</span><h2>${p.name}</h2><p>${p.description}</p><div class="pack-meta"><span>${icon('cards')} ${CARDS.filter(c=>c.pack===p.id).length} kort</span><span>${icon('users')} ${p.min}+ spillere</span></div>${btn('select-pack',state.pack===p.id?'Aktiv spilpakke':'Spil med pakken',state.pack===p.id?'check':'arrow',`button ${state.pack===p.id?'secondary':'primary'}`,`data-id="${p.id}"`)}</div></article>`).join('')}</div>`;}
function ideasPage(){return pageHeader('LIDT INSPIRATION TIL BORDET','Hvad skal vi lave?','Prøv et færdigt oplæg, og gør aftenen til jeres egen.')+`<div class="selection-grid">${IDEAS.map((idea,i)=>`<article class="idea-card"><span class="idea-number">0${i+1}</span><div class="selection-icon">${icon(ENGINES.find(e=>e.id===idea.engine).icon)}</div><h2>${idea.title}</h2><p>${idea.text}</p>${btn('idea','Brug oplægget','arrow','button secondary',`data-id="${i}"`)}</article>`).join('')}</div>`;}
function studioPage(){return pageHeader('DIT SPIL. DINE REGLER.','Kreativt kaos starter her.','Skriv egne kort, vælg kategori og giv dem en plads i spillet.',btn('new-card','Opret kort','plus','button primary'))+`<div class="studio-banner">${icon('studio')}<div><h2>Gør aftenen personlig</h2><p>Egne kort blandes ind i puljen sammen med spilpakkens kort. Eksportér dem i Indstillinger, hvis du vil dele.</p></div><span class="pill">${state.customCards.length} egne kort</span></div>${state.customCards.length?`<div class="board-grid">${state.customCards.map(c=>`<article class="board-card"><span class="eyebrow">${category(c.category).name} · ${LEVELS[c.level-1]}</span><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p><div class="board-card-actions">${btn('edit-card','Rediger','studio','text-button',`data-id="${c.id}"`)}${btn('delete-custom','','trash','icon-button',`data-id="${c.id}" aria-label="Slet ${esc(c.title)}"`)}</div></article>`).join('')}</div>`:`<div class="empty-state">${icon('cards')}<h2>Hvad ville få dit bord til at grine?</h2><p>Din første udfordring er kun et kort væk.</p>${btn('new-card','Lav dit første kort','plus','button secondary')}</div>`}`;}
function designPage(){return pageHeader('SÆT STEMNINGEN','Et look til hver aften.','Sort krom, blødt lys og lige præcis den energi, I er til.')+`<div class="theme-grid">${[['neon','Neon Casino','Lilla neon. Guld. Held i spil.'],['red','Red Room','Dybe røde toner. Tættere på.'],['chaos','Party Chaos','Pink energi. Alt kan ske.'],['chrome','Black Chrome','Grafit. Cyan. Fuld kontrol.']].map(([id,name,text])=>`<button class="theme-card ${id} ${state.settings.theme===id&&!state.settings.autoTheme?'chosen':''}" data-theme="${id}"><div class="theme-preview"><span>&</span><i></i><i></i><i></i></div><h2>${name}</h2><p>${text}</p></button>`).join('')}</div><div class="settings-panel">${settingRow('autoTheme','Følg spilpakken','Lad farverne skifte automatisk med den valgte spilpakke.')}${settingRow('motion','Animationer','Spin, rul og afslør resultater med bevægelse.')}</div>`;}
function settingRow(key,title,description){return `<label class="setting-row"><span><strong>${title}</strong><small>${description}</small></span><input type="checkbox" role="switch" data-setting="${key}" ${state.settings[key]?'checked':''}/></label>`;}
function settingsPage(){return pageHeader('GØR DET TIL JERES AFTEN','Indstillinger','Alt gemmes på denne enhed. Ingen konto, ingen reklamer.')+`<div class="settings-panel"><h2>Spiloplevelse</h2>${settingRow('sound','Spillyd','Små lydsignaler ved spin, resultater og timer.')}${settingRow('motion','Animationer','Skru ned for bevægelsen, hvis I foretrækker ro.')}${settingRow('smart','Smart Random','Undgå gentagelser, og fordel kategorierne mellem spillerne.')}${settingRow('alcohol','Drikkevalg · 18+','Tilføj en valgfri skål til kortene. Alle drikke fungerer.')}<label class="setting-row"><span><strong>Antal runder</strong><small>En runde giver hver spiller én tur.</small></span><select id="rounds">${[3,5,10,20].map(n=>option(n,`${n} runder`,state.rounds)).join('')}</select></label></div><div class="settings-panel"><h2>Gem, flyt og fortsæt</h2><p>Eksportér aftenens spillere, historik, Action Board og egne kort som en fil. Import erstatter den gemte aften på denne enhed.</p><div class="button-row">${btn('export','Eksportér aften','download','button secondary')}${btn('import','Importér aften','upload','button secondary')}<input type="file" id="import-file" accept="application/json,.json" hidden/></div></div><div class="settings-panel"><h2>En god aften er for alle</h2><p>Alle udfordringer er frivillige. Aftal niveauet sammen, hold pause, og brug Spring over, når det passer jer. Appen fungerer lige så godt med sodavand.</p>${btn('setup','Start en ny aften','plus','button secondary')}</div>`;}
function summaryPage(){const counts=CATEGORIES.map(c=>({...c,count:state.history.filter(h=>h.card.category===c.id).length})).sort((a,b)=>b.count-a.count);return `<section class="summary-page">${icon('trophy','summary-trophy')}<span class="eyebrow">GAME COMPLETE</span><h1>Det var en <em>god aften.</em></h1><p>Tak for spillet. De bedste øjeblikke bliver ved bordet.</p><div class="summary-stats"><div><strong>${state.round}</strong><span>Runder</span></div><div><strong>${state.history.length}</strong><span>Udfordringer</span></div><div><strong>${state.stats.wildcards}</strong><span>Wildcards</span></div><div><strong>${state.board.length}</strong><span>Kort på board</span></div></div><p>Mest spillede kategori: <strong>${counts[0].count?counts[0].name:'Ingen endnu'}</strong> · ${state.stats.skipped} ture sprunget over</p><div class="button-row">${btn('finale','Start finalen','flag','button primary',state.board.some(c=>!c.done)?'':'disabled')}${btn('setup','Spil igen','play','button secondary')}${btn('export','Gem aftenen','download','button secondary')}</div><div class="finale-history">${recentPanel()}</div></section>`;}
function finalePage(){const pending=state.board.filter(c=>!c.done),item=pending[Math.min(finaleIndex,Math.max(0,pending.length-1))];return pageHeader('ÉT KORT AD GANGEN','Den store finale',`${state.board.filter(c=>c.done).length} af ${state.board.length} kort er gennemført.`)+(!item?`<div class="empty-state">${icon('trophy')}<h2>I kom hele vejen!</h2><p>Alle kort på Action Board er gennemført.</p>${btn('go-play','Tilbage til aftenen','arrow','button primary')}</div>`:`<article class="finale-card result-card" style="--card-color:${category(item.card.category).color}"><span class="eyebrow">${category(item.card.category).name} · ${esc(state.players.find(p=>p.id===item.playerId)?.name||'Alle')}</span><h2>${esc(item.card.title)}</h2><p>${esc(item.card.text)}</p><div class="button-row">${btn('finale-done','Gennemført','check','button primary',`data-id="${item.id}"`)}${btn('finale-skip','Tag næste kort','arrow','button secondary')}</div></article>`);}
function modalHTML(){let content='',title='';
 if(modal==='setup'){title=state.started?'Start en ny aften':'Hvem er med i aften?';content=`<p>2–16 spillere. Ét navn på hver linje.</p>${state.started?'<p class="notice">Den aktuelle runde, historik og Action Board nulstilles. Egne kort og indstillinger bevares.</p>':''}<form id="setup-form"><label for="names">Spillere</label><textarea id="names" rows="5" placeholder="Tobias&#10;Pernille&#10;Martin&#10;Sofie" required autofocus>${state.players.map(p=>esc(p.name)).join('\n')}</textarea><label for="setup-rounds">Hvor lang skal aftenen være?</label><select id="setup-rounds">${[3,5,10,20].map(n=>option(n,`${n} runder`,state.rounds)).join('')}</select><p class="form-error" role="alert" id="form-error"></p><button class="button primary full" type="submit">${icon('play')} Lad aftenen begynde</button></form>`;}
 if(modal==='players'){title='Holdet ved bordet';content=`<p>Navne kan ændres under spillet. Tilføj nye spillere nederst.</p><form id="players-form">${state.players.map((p,i)=>`<label for="player-${i}">Spiller ${i+1}</label><input id="player-${i}" data-player-name="${p.id}" value="${esc(p.name)}" maxlength="24" required/>`).join('')}<label for="new-player">Ny spiller</label><input id="new-player" placeholder="Navn" maxlength="24"/><p class="form-error" role="alert" id="form-error"></p><button class="button primary full" type="submit">${icon('check')} Gem spillere</button></form>`;}
 if(modal==='help'){title='Sådan spiller I';content=`<div class="help-step"><b>01</b><div><h3>Saml holdet</h3><p>Tilføj navnene, vælg en spilpakke og find et niveau, alle har lyst til.</p></div></div><div class="help-step"><b>02</b><div><h3>Lad skæbnen spille</h3><p>Spin, rul, træk et kort eller åbn en boks. Random kan sende jer videre til en anden spilmotor.</p></div></div><div class="help-step"><b>03</b><div><h3>Tag udfordringen</h3><p>Gennemfør den nu, eller gem den på Action Board. Tryk Næste spiller, når I er klar.</p></div></div><div class="help-step"><b>04</b><div><h3>Slut med en finale</h3><p>Afvikl de gemte kort ét efter ét. Game Master kan justere tempo og kategori undervejs.</p></div></div><p class="notice">Der er ingen penge, indsatser eller gambling. Alle udfordringer er frivillige.</p>`;}
 if(modal==='master'){title='Du er Game Master';content=`<p>Skru på aftenen, mens spillet fortsætter.</p><label for="master-category">Aktiv kategori</label><select id="master-category">${option('all','Alle kategorier',state.category)}${CATEGORIES.map(c=>option(c.id,c.name,state.category)).join('')}</select><div class="master-grid">${btn('force-spin','Tving et spin','slots','button secondary')}${btn('bonus','Giv bonus','star','button secondary')}${btn('wildcard','Aktivér wildcard','flame','button secondary')}${btn('chaos','Chaos Mode','bolt','button secondary')}${btn('add-master-card','Tilføj kort på board','plus','button secondary')}${btn('skip','Spring spiller over','arrow','button secondary')}</div>${btn('finish','Afslut spillet','flag','button secondary full')}`;}
 if(modal==='edit-card'){const c=state.customCards.find(c=>c.id===editId)||{title:'',text:'',category:'challenge',level:2,pack:'all',seconds:0};title=editId?'Rediger dit kort':'Skab et nyt kort';content=`<form id="card-form"><label for="card-title">Kortets titel</label><input id="card-title" maxlength="65" value="${esc(c.title)}" placeholder="Fx Bordets hemmelige talent" required autofocus/><label for="card-text">Udfordring eller spørgsmål</label><textarea id="card-text" rows="4" maxlength="700" required placeholder="Hvad skal spilleren gøre?">${esc(c.text)}</textarea><div class="form-grid"><div><label for="card-category">Kategori</label><select id="card-category">${CATEGORIES.map(x=>option(x.id,x.name,c.category)).join('')}</select></div><div><label for="card-level">Intensitet</label><select id="card-level">${LEVELS.map((l,i)=>option(i+1,l,c.level)).join('')}</select></div><div><label for="card-pack">Spilpakke</label><select id="card-pack">${option('all','Alle pakker',c.pack)}${PACKS.map(p=>option(p.id,p.name,c.pack)).join('')}</select></div><div><label for="card-seconds">Timer</label><select id="card-seconds">${[0,10,30,45,60,90].map(n=>option(n,n?`${n} sekunder`:'Ingen timer',c.seconds)).join('')}</select></div></div><label for="card-next">Efter kortet</label><select id="card-next">${option('','Næste spiller',c.nextEngine||'')}${ENGINES.filter(e=>e.id!=='random').map(e=>option(e.id,'Fortsæt med '+e.name,c.nextEngine)).join('')}</select><button class="button primary full" type="submit">${icon('check')} Gem kortet</button></form>`;}
 if(modal==='detail'){const item=modalData;title=esc(item.card.title);content=`<span class="eyebrow">${category(item.card.category).name} · ${LEVELS[item.card.level-1]}</span><p class="detail-text">${esc(item.card.text)}</p><p>${esc(item.playerName||state.players.find(p=>p.id===item.playerId)?.name||'Alle')} · Runde ${esc(item.round)}</p>${item.sourceId?'':btn('save-history','Gem på Action Board','plus','button primary',`data-id="${item.id}"`)}`;}
 if(modal==='import-confirm'){title='Erstat den gemte aften?';content=`<p>Filen indeholder ${modalData.players.length} spillere, ${modalData.board.length} boardkort og ${modalData.customCards.length} egne kort. Den erstatter den nuværende aften på denne enhed.</p>${btn('confirm-import','Importér og fortsæt','upload','button primary full')}`;}
 if(modal==='finish-confirm'){title='Er I klar til finalen?';content=`<p>Afslut de aktive runder, og se aftenens resultater. Jeres kort og historik bliver gemt.</p>${btn('confirm-finish','Afslut aftenen','flag','button primary full')}`;}
 if(modal==='alcohol'){title='Drikkevalg · kun for voksne';content=`<p>Denne indstilling er for deltagere på 18 år eller derover. Den tilføjer en valgfri skål til kortene. Man vælger altid selv sin drik og kan springe over.</p>${btn('confirm-alcohol','Vi er 18+ · Aktivér','check','button primary full')}`;}
 return `<dialog class="modal" aria-labelledby="modal-title"><div class="modal-header"><h2 id="modal-title">${title}</h2>${btn('close-modal','','close','icon-button','aria-label="Luk vindue"')}</div>${content}</dialog>`;
}
function openModal(name,data){modal=name;modalData=data||null;render();}
function closeModal(){modal='';modalData=null;render();}
function setEngine(id){if(busy)return;state.engine=id;selectedBox=-1;page='play';persist();render();}
async function play(box=-1){
 if(busy||state.paused||state.result)return;
 if(!state.started){openModal('setup');return;}
 if(!cardPool(state).length){toast('Ingen kort på det niveau i kategorien. Vælg en anden kategori eller intensitet.');return;}
 busy=true;selectedBox=box;state.chain.push(engine().name);const playedEngine=state.engine;render();tone(350);
 if(playedEngine==='random'){await delay(850);const next=ENGINES[randomInt(5)];state.engine=next.id;busy=false;selectedBox=-1;persist();render();toast(`Random valgte ${next.name}. Fortsæt kæden!`);return;}
 let selectedCategory;
 if(playedEngine==='slots'){const symbols=['bolt','chat','users','star','flame'];for(let i=0;i<3;i++){await delay(330);slotValues[i]=symbols[randomInt(symbols.length)];const reel=document.querySelector(`.reel-${i}`);if(reel){reel.classList.remove('rolling');reel.querySelector('.reel-main').innerHTML=icon(slotValues[i]);}tone(430+i*160);}selectedCategory=CATEGORIES[symbols.indexOf(slotValues[1])].id;
 }else if(playedEngine==='dice'){await delay(1050);diceValues=[randomInt(6)+1,randomInt(6)+1];document.querySelector('#mechanism').innerHTML=mechanism();selectedCategory=CATEGORIES[(diceValues[0]+diceValues[1])%5].id;await delay(450);
 }else if(playedEngine==='roulette'){const index=randomInt(5),target=360-(index*72+36);wheelAngle=(Math.floor(wheelAngle/360)+4)*360+target;requestAnimationFrame(()=>document.querySelector('.roulette-wheel')?.style.setProperty('--wheel-angle',`${wheelAngle}deg`));await delay(2100);selectedCategory=CATEGORIES[index].id;
 }else await delay(playedEngine==='mystery'?850:750);
 const card=drawCard(state,selectedCategory);busy=false;if(!card){render();toast('Ingen kort tilgængelige. Skift kategori.');return;}
 recordResult(state,card,playedEngine);timerRemaining=card.seconds;stopTimer();persist();render();tone(900);
}
function next(skipped=false){if(!state.started||busy)return;stopTimer();timerRemaining=0;modal='';advanceTurn(state,skipped);persist();render();}
function updateTimer(){const value=document.querySelector('#timer-value'),label=document.querySelector('#timer-label');if(value)value.textContent=timerRemaining?`${timerRemaining}s`:'Tiden er gået';if(label)label.textContent=timerRunning?'Pause timer':timerRemaining?'Start timer':'Start igen';}
function toggleTimer(){if(!state.result?.card.seconds)return;if(timerRunning){stopTimer();updateTimer();return;}if(!timerRemaining)timerRemaining=state.result.card.seconds;timerRunning=true;updateTimer();timerId=setInterval(()=>{timerRemaining--;if(timerRemaining<=0){stopTimer();tone(1050);toast('Tiden er gået!');}updateTimer();},1000);}
function exportSession(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`leg-druk-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Aftenen er eksporteret.');}
function masterDraw(cat,boardOnly=false){const source={...state,category:cat||state.category};const c=drawCard(source,cat);state.used=source.used;if(!c){toast('Ingen kort til det valgte niveau.');return;}const r=recordResult(state,c,state.engine);if(boardOnly)addToBoard(state,r);modal='';page='play';timerRemaining=c.seconds;stopTimer();persist();render();}
const actions={
 'continue-chain':()=>{const target=state.result?.card.nextEngine;if(!target)return;addToBoard(state);state.result=null;state.engine=target;stopTimer();timerRemaining=0;persist();render();toast('Kortet er gemt. Samme spiller fortsætter kæden.');},
 collapse:()=>{collapsed=!collapsed;render();},sound:()=>{state.settings.sound=!state.settings.sound;persist();render();tone();},help:()=>openModal('help'),setup:()=>openModal('setup'),players:()=>openModal(state.started?'players':'setup'),packs:()=>{page='packs';render();},'go-play':()=>{page='play';drawer=false;render();},play:()=>play(),
 pause:()=>{if(!state.started||busy)return;state.paused=!state.paused;if(state.paused)stopTimer();persist();render();},skip:()=>next(true),next:()=>next(),timer:()=>toggleTimer(),save:()=>{if(addToBoard(state)){persist();render();toast('Kortet er gemt på Action Board.');}},drawer:()=>{drawer=true;render();},'close-drawer':()=>{drawer=false;render();},'close-modal':()=>closeModal(),
 'select-pack':el=>{const p=PACKS.find(p=>p.id===el.dataset.id);if(state.started&&state.players.length<p.min){toast(`${p.name} kræver mindst ${p.min} spillere.`);return;}state.pack=el.dataset.id;state.category='all';persist();page='play';render();toast(`${pack().name} er klar.`);},
 master:()=>openModal('master'),'force-spin':()=>{if(state.result){toast('Afslut først det aktuelle kort med Næste spiller.');return;}modal='';state.engine='slots';page='play';render();play();},bonus:()=>masterDraw('bonus'),wildcard:()=>masterDraw('wildcard'),chaos:()=>{if(state.players.length<3){toast('Chaos Mode kræver mindst tre spillere.');return;}state.settings.autoTheme=false;state.settings.theme='chaos';state.level=5;state.pack='chaos';state.category='all';modal='';persist();render();toast('Chaos Mode er aktiv!');},'add-master-card':()=>masterDraw(null,true),
 finish:()=>openModal('finish-confirm'),'confirm-finish':()=>{stopTimer();state.finished=true;state.paused=false;modal='';page='play';persist();render();},
 'board-done':el=>{const c=state.board.find(c=>c.id===el.dataset.id);c.done=!c.done;persist();render();},'remove-card':el=>{state.board=state.board.filter(c=>c.id!==el.dataset.id);persist();render();toast('Kortet er fjernet fra boardet.');},'move-up':el=>{moveBoardCard(state,el.dataset.id,-1);persist();render();},'move-down':el=>{moveBoardCard(state,el.dataset.id,1);persist();render();},
 finale:()=>{page='finale';drawer=false;finaleIndex=0;render();},'finale-done':el=>{state.board.find(c=>c.id===el.dataset.id).done=true;finaleIndex=0;persist();render();},'finale-skip':()=>{const count=state.board.filter(c=>!c.done).length;finaleIndex=count?(finaleIndex+1)%count:0;render();},
 idea:el=>{const i=IDEAS[Number(el.dataset.id)];if(state.started&&state.players.length<PACKS.find(p=>p.id===i.pack).min){toast('Tilføj mindst tre spillere for at bruge dette oplæg.');return;}state.pack=i.pack;state.engine=i.engine;state.level=i.level;state.category='all';page='play';persist();render();toast('Oplægget er klar. God fornøjelse!');},
 'new-card':()=>{editId=null;openModal('edit-card');},'edit-card':el=>{editId=el.dataset.id;openModal('edit-card');},'delete-custom':el=>{state.customCards=state.customCards.filter(c=>c.id!==el.dataset.id);persist();render();toast('Dit kort er slettet.');},'save-history':el=>{const r=state.history.find(h=>h.id===el.dataset.id);toast(addToBoard(state,r)?'Kortet er gemt.':'Kortet er allerede på boardet.');persist();closeModal();},export:()=>exportSession(),import:()=>document.querySelector('#import-file').click(),
 'confirm-import':()=>{state=modalData;modal='';modalData=null;page='play';stopTimer();timerRemaining=state.result?.card.seconds||0;persist();render();toast('Aftenen er importeret.');},'confirm-alcohol':()=>{state.settings.alcohol=true;persist();closeModal();}
};
app.addEventListener('click',event=>{const el=event.target.closest('button,a[data-page]');if(!el||el.disabled)return;if(busy)return;if(el.dataset.page){page=el.dataset.page;render();return;}if(el.dataset.engine){setEngine(el.dataset.engine);return;}if(el.dataset.box!==undefined){play(Number(el.dataset.box));return;}if(el.dataset.history){openModal('detail',state.history.find(h=>h.id===el.dataset.history));return;}if(el.dataset.openCard){openModal('detail',state.board.find(c=>c.id===el.dataset.openCard));return;}if(el.dataset.theme){state.settings.theme=el.dataset.theme;state.settings.autoTheme=false;persist();render();return;}actions[el.dataset.action]?.(el);});
app.addEventListener('click',e=>{if(e.target.classList.contains('drawer-backdrop')){drawer=false;render();}});
app.addEventListener('cancel',e=>{e.preventDefault();closeModal();},true);
app.addEventListener('input',e=>{if(e.target.id==='intensity'){state.level=Number(e.target.value);document.querySelector('.intensity-header strong').textContent=LEVELS[state.level-1];e.target.setAttribute('aria-valuetext',LEVELS[state.level-1]);persist();}});
app.addEventListener('change',async e=>{const el=e.target;
 if(el.dataset.setting){const key=el.dataset.setting;if(key==='alcohol'&&el.checked){el.checked=false;openModal('alcohol');return;}state.settings[key]=el.checked;persist();render();}
 if(el.id==='rounds'){state.rounds=Number(el.value);if(state.round>state.rounds)state.round=state.rounds;persist();}
 if(el.id==='master-category'){state.category=el.value;persist();}
 if(el.dataset.assign){state.board.find(c=>c.id===el.dataset.assign).playerId=el.value;persist();}
 if(el.id==='board-filter'){document.querySelectorAll('.board-card').forEach(card=>{card.hidden=el.value==='pending'?card.classList.contains('completed'):el.value==='done'?!card.classList.contains('completed'):false;});}
 if(el.id==='import-file'&&el.files[0]){try{if(el.files[0].size>2_000_000)throw new Error();const data=JSON.parse(await el.files[0].text());if(data.version!==1||!Array.isArray(data.players))throw new Error();openModal('import-confirm',normalizeState(data));}catch{toast('Filen kunne ikke læses. Vælg en gyldig LEG & DRUK-eksport.');}}
});
app.addEventListener('submit',e=>{e.preventDefault();const form=e.target,val=id=>document.getElementById(id).value;
 if(form.id==='setup-form'){try{const nextState=beginSession(state,val('names').split(/\n|,/),Number(val('setup-rounds')));if(nextState.players.length<pack().min)throw new Error(`${pack().name} kræver mindst ${pack().min} spillere.`);state=nextState;stopTimer();timerRemaining=0;modal='';page='play';persist();render();toast('Holdet er klar. Lad aftenen spille!');}catch(error){document.querySelector('#form-error').textContent=error.message;}}
 if(form.id==='players-form'){const names=[...form.querySelectorAll('[data-player-name]')].map(i=>({id:i.dataset.playerName,name:i.value.trim()})),newName=val('new-player').trim();if(newName)names.push({id:uid(),name:newName});if(names.length>16||names.some(p=>!p.name)||new Set(names.map(p=>p.name.toLowerCase())).size!==names.length){document.querySelector('#form-error').textContent='Brug 2–16 forskellige navne.';return;}state.players=names;persist();closeModal();}
 if(form.id==='card-form'){const card={id:editId||`custom-${uid()}`,title:val('card-title').trim(),text:val('card-text').trim(),category:val('card-category'),level:Number(val('card-level')),pack:val('card-pack'),seconds:Number(val('card-seconds')),nextEngine:val('card-next')};if(!card.title||!card.text)return;if(editId)state.customCards=state.customCards.map(c=>c.id===editId?card:c);else state.customCards.push(card);persist();modal='';page='studio';render();toast('Dit kort er klar til spil.');}
});
let dragId;
app.addEventListener('dragstart',e=>{const card=e.target.closest('[data-board-id]');if(card){dragId=card.dataset.boardId;e.dataTransfer.setData('text/plain',dragId);e.dataTransfer.effectAllowed='move';}});
app.addEventListener('dragover',e=>{if(e.target.closest('[data-board-id]'))e.preventDefault();});
app.addEventListener('drop',e=>{const target=e.target.closest('[data-board-id]');if(!target||!dragId)return;e.preventDefault();const from=state.board.findIndex(c=>c.id===dragId),to=state.board.findIndex(c=>c.id===target.dataset.boardId);if(from>=0&&to>=0){const [card]=state.board.splice(from,1);state.board.splice(to,0,card);persist();render();}dragId=null;});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&drawer){drawer=false;render();}if(e.code==='Space'&&!modal&&page==='play'&&!['INPUT','TEXTAREA','SELECT','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();if(!state.result)play();}});
window.addEventListener('hashchange',()=>{if(location.hash==='#play'){page='play';render();}});
render();
if('serviceWorker' in navigator&&location.hostname!=='127.0.0.1'&&location.hostname!=='localhost')navigator.serviceWorker.register('./sw.js').catch(()=>{});


